### ISSUE TITLE
How to use it with kogrid

### ISSUE THREAD

**Issue by satyanshu** [benschulz/ko-grid-export#1]
What is the way to use it with kogrid. Can you provide a simple code example for this.  I have included the ko-grid-export.js and css in my page. On my gridOptions i am using the config: 'export-basic-config'. but it is not working. It would be very helpful for users if you can provide a working code for this.

**Comment by benschulz** [comment]
To get started I suggest you take a look at one of the two [simple, self contained examples](https://github.com/benschulz/ko-grid-examples/tree/master/src/sscces) in the examples project and then adjust to your needs.

To add export support to the provided sscces simply add the two extensions "toolbar" and "export" to the config. The relevant snippet should look something like this:

```
window.ko.bindingHandlers.grid.config['example-config'] = {
    extensions: {
        filtering: {},
        sorting: {},
        toolbar: {},
        export: {}
    }
};
```

**Tip**: Use [ko-grid-bundle](https://github.com/benschulz/ko-grid-bundle) rather than manually including any extensions. All you need to get started are the `ko-grid-bundle.js` and the `ko-grid-bundle.css`. (If you're concerned with the size of the resulting JS/CSS you can still build your own reduced bundle once you're ready to deploy.)

Please let me know if there is anything more I can help you with.

**Comment by benschulz** [comment]
I consider this issue closed. Feel free to reopen it, if you need further assistence.
